### ISSUE TITLE
the pump doesn't pump to Prometheus

### ISSUE THREAD

**Issue by tirelibirefe** [TykTechnologies/tyk-helm-chart#164]
Helllo,
Please look at here >>> [https://community.tyk.io/t/tyk-pump-cannot-pump/4936/6](https://community.tyk.io/t/tyk-pump-cannot-pump/4936/5) 
When I enable pump in values file, it doesn't pump to Prometheus.

Please advise...

Regards

**Comment by mjpieters** [comment]
> ```yaml
> pump:
>   extraEnvs:
>     TYK_PMP_PUMPS_PROMETHEUS_TYPE: prometheus
>     TYK_PMP_PUMPS_PROMETHEUS_META_ADDR: ":9090"
>     TYK_PMP_PUMPS_PROMETHEUS_META_PATH: "/metrics"
> ```

Sorry, use `name:` and `value:` keys:

```yaml
pump:
  extraEnvs:
  - name: TYK_PMP_PUMPS_PROMETHEUS_TYPE
    value: prometheus
  - name: TYK_PMP_PUMPS_PROMETHEUS_META_ADDR
    value: ":9090"
  - name: TYK_PMP_PUMPS_PROMETHEUS_META_PATH
    value: "/metrics"
```
