### ISSUE TITLE
tyk-ce cannot connect to secure backend in Kubernetes

### ISSUE THREAD

**Issue by tirelibirefe** [TykTechnologies/tyk-helm-chart#169]
Hello,
I've a tyk-ce gw and tyk operator in Kubernetes (AWS EKS) environment which was installed by using Helm chart. In my environment ssl termination is handled by LB level by ALB.

There are some https backend services like Kibana or Kubernetes dashboard in Kubernetes. These services must be exposed by tyk ingress.
![image](https://user-images.githubusercontent.com/45227339/138349695-e40a9b03-1780-4384-9172-0d92acfd47b4.png)

The following apidefinition can be a reference.

```
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: kibana
  namespace: eck
  labels:
    template: "true"
spec:
  name: kibana
  protocol: http
  listen_port: 80
  use_keyless: true
  active: true
  proxy:
    target_url: https://kibana-kb-http.eck.svc.cluster.local:5601
    listen_path: /kibana
    strip_listen_path: true
    transport:
      ssl_insecure_skip_verify: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        paths:
          black_list: []
          ignored: []
          white_list: []
```

Tyk cannot connect to HTTPS services in Kubernetes. I need to your advises. If there is someone who could have connected to the secure backends by the way, advises would be very helpful.

Thanks & Regards
