### ISSUE TITLE
Can not deploy helm chart using different release name

### ISSUE THREAD

**Issue by raman-nbg** [TykTechnologies/tyk-helm-chart#175]
I'm using `tyk-pro` with the portal. I have defined separate domains/hosts for dashboard (`dashboard.example.com`) and portal (`portal.example.com`).

When I access `portal.example.com/portal` I see the following:

![image](https://user-images.githubusercontent.com/20013423/140340400-5187c1fe-4c8f-45fa-9165-14a633cd8d12.png)

As I can see in the Browser's developer tools the index.html requests resources (CSS, JS, ...) from the following paths:

![image](https://user-images.githubusercontent.com/20013423/140342585-9cd7663d-bd0a-4638-aaea-b00b8547d751.png)

It seems that the base path `/portal` is missing.

This is my helm configuration for the portal:
```yaml
portal:
  bootstrap: true
  path: /portal # the base path
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      - portal.example.com
    tls:
      - secretName: tyk-portal-tls
        hosts:
          - portal.example.com
```

If I just access `portal.example.com` (without the `portal`) then I get a 404 from my NGINX ingress controller. 

I also tried to configure the portal without any base path (just `path: /`). In this case `portal.example.com` shows the dashboard and not the portal.

Am I missing something? Preferred option would be to access the portal directly using `portal.example.com`. I couldn't find anything about this in the [official docs](https://tyk.io/docs/tyk-self-managed/tyk-helm-chart/#tyk-developer-portal).

**Comment by rewsmith** [comment]
Hi Raman,

I'm guessing this is because you haven't set the portal cname in your helm dashboard config?  Example below ....

```
# Dashboard Organisation information.
  org:
    name: Default Org
    # The hostname to bind the Portal to.
    cname: portal.example.com
```

Let us know how you get on.

regards,
Andy
