### ISSUE TITLE
Tyk Pro - (Re-Bootstrapping and Chart NOT Allowing for Empty Redis Password)

### ISSUE THREAD

**Issue by klaus385** [TykTechnologies/tyk-helm-chart#210]
We are trying to migrate from the Helm Chart maintained fork as mentioned on #64. However, we encounter two problems when doing so and pointing the deployment with the same values to use this upstream chart.

## Issues

1. Error stating -> 

```
time="Jun 15 22:22:51" level=warning msg="Reconnecting storage: Redis is either down or ws not configured" prefix=pub-sub
```
Even though the Redis instance is accessible from the location where the Tyk Gateway is deployed. Also, when we update our fork to allow for an empty password for the connection to Redis we do NOT see this error. This leads me to think that even when I set `redisPass` in the values to `""`it's **NOT** allowing for Redis connection without a password.

2. Re-Bootstrapping ->

What I mean by this is that the following shown in the screenshot is prompted to me as if the currently deployed setup for Tyk-Pro wasn't already bootstrapped.

<img width="970" alt="Screen Shot 2022-06-13 at 12 48 10 PM" src="https://user-images.githubusercontent.com/12820328/174875662-6b2a13b9-b363-418d-b500-10db830b065e.png">

## Current Configuration

Using Tyk-Operator, Tyk-Pro 0.8.2, and Tyk Pro Self-Managing License.

### Tyk Pro Values

```yaml
bootstrap: false
portal:
  bootstrap: false
  path: "/portal"
redis:
  enableCluster: true
dash:
  bootstrap: false
  resources:
    limits:
      cpu: 500m
      memory: 512M
    requests:
      cpu: 500m
      memory: 512M
  service:
    type: NodePort
    port: 3000
  ingress:
    enabled: true
    annotations:
      {
        kubernetes.io/ingress.class: alb,
        alb.ingress.kubernetes.io/scheme: internet-facing,
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]',
      }
    path: /*
  extraEnvs:
    - name: TYK_DB_ENABLEDELETEKEYBYHASH
      value: "true"
    - name: TYK_DB_ENABLEUPDATEKEYBYHASH
      value: "true"
    - name: TYK_DB_ENABLEHASHEDKEYSLISTING
      value: "true"
    - name: TYK_DB_HOSTCONFIG_GENERATEHTTPS
      value: "true"

gateway:
  sharding:
    enabled: true
  kind: Deployment
  tls: false
  extraEnvs:
    - name: TYK_GW_ENABLEHASHEDKEYSLISTING
      value: "true"
    - name: TYK_GW_POLICIES_ALLOWEXPLICITPOLICYID
      value: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  ingress:
    enabled: true
    annotations:
      {
        kubernetes.io/ingress.class: alb,
        alb.ingress.kubernetes.io/scheme: internet-facing,
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]',
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300,
      }
    path: /*
  service:
    type: NodePort
    port: 8080
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - gateway-tyk-pro
          topologyKey: kubernetes.io/hostname

pump:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
  extraEnvs:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: TYK_PMP_PUMPS_DOGSTATSD_TYPE
      value: "dogstatsd"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_ADDRESS
      value: "$(HOST_IP):8125"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_NAMESPACE
      value: "tykpump"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_ASYNCUDS
      value: "true"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_ASYNCUDSWRITETIMEOUTSECONDS
      value: "2"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_BUFFERED
      value: "true"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_BUFFEREDMAXMESSAGES
      value: "32"
    - name: TYK_PMP_PUMPS_DOGSTATSD_META_SAMPLERATE
      value: "1"
    - name: TYK_PMP_UPTIMEPUMPCONFIG_MONGOURL
      valueFrom:
        secretKeyRef:
          key: mongoURL
          name: secrets-tyk-pro
    - name: TYK_PMP_MONGO_MONGOURL
      valueFrom:
        secretKeyRef:
          key: mongoURL
          name: secrets-tyk-pro
    - name: TYK_PMP_MONGOAGG_MONGOURL
      valueFrom:
        secretKeyRef:
          key: mongoURL
          name: secrets-tyk-pro
```

### Tyk Operator Values

```yaml
replicaCount:
  1
  # loads enviroment variables to the operator.
envFrom:
  - secretRef:
      name: tyk-operator-conf
envVars:
  - name: TYK_HTTPS_INGRESS_PORT
    value: "8443"
  - name: TYK_HTTP_INGRESS_PORT
    value: "8080"

image:
  repository: tykio/tyk-operator
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

annotations: {}
podAnnotations: {}
podSecurityContext:
  allowPrivilegeEscalation: false
resources: {}

#specify necessary resources for kube-rbac-proxy container
rbac:
  resources: {}
  # specify custom/internal repo name for kube-rbac-proxy container
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.8.0"
```

Look forward to hearing back and hopefully getting these issues resolved.
