### ISSUE TITLE
Helm Values Unclear for User Provided Secrets

### ISSUE THREAD

**Issue by ghost** [TykTechnologies/tyk-helm-chart#281]
Morning,

I'm using the `tyk-helm/tyk-headless` chart version `0.14.0`. Within the `values.yaml` file there is this section:

```yaml
secrets:
  # tyk.conf node_secret
  # tyk.conf secret
  APISecret: CHANGEME
  # If you don't want to store plaintext secrets in the Helm value file and would
  # rather provide the k8s Secret externally please populate the value below
  useSecretName: ""
```

I interpreted the comment to mean provide an external `secret` using `useSecretName` for just the `APISecret`.  However, even if I provide secrets for `redis` within the `helm` values, it is ignored and sought from the external secret.  The `redis` section looks like this:

```yaml
redis:
  addrs:
    - redis.redis-01.svc.cluster.local:26379
  pass: "<snip>
  enableCluster: false
  enableSentinel: true
  sentinelPass: "<snip>"
  masterName: "redis-master"
```

The pods are stuck in `CreateContainerConfigError` and the error message I get when using `kubectl describe pod` is:

```bash
Error: couldn't find key redisSentinelPass in Secret tyk/tyk-api
```

There are two problems:

1) It's unclear that when providing an external secret via `useSecretName` that it will replace the secrets for `redis` defined later on. But what else? MongoURL?
2) The keys or format needed for the user defined secrets are not defined in the comments e.g.:
* `APISecret`
* `redisPass`
* `redisSentinelPass`

I'm happy to propose some changes but need a way to determine what secrets are covered and which are just config parameters.

Update: fixed typos and clarified language.
