### ISSUE TITLE
Invalid ingress will crash the ingress listener so controller needs restarting

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk-helm-chart#30]
If you supply an invalid ingress like the one in the example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
spec:
  rules:
    - host: cafe.example.com
```

This is perfectly valid, but the controller expects a path, which causes a panic. Unfortunately the controller does not recover from this and needs restarting.
