### ISSUE TITLE
Example ingress does not work

### ISSUE THREAD

**Issue by lonelycode** [TykTechnologies/tyk-helm-chart#31]
Linked to #30, the ingress in the documentation will actually crash the controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
spec:
  rules:
    - host: cafe.example.com
```

It needs a path element:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80
```
